# Generated by Django 2.2.7 on 2020-05-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0002_auto_20200501_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
