# Generated by Django 2.2.7 on 2020-05-02 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0017_auto_20200502_1539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userupload', '0003_delete_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
