# Generated by Django 2.2.7 on 2020-05-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0006_auto_20200502_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
