# Generated by Django 2.2.7 on 2020-05-16 04:39

from django.db import migrations, models
import userupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0007_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=userupload.models.user_directory_path, validators=[userupload.models.validate_file_size]),
        ),
    ]
