# Generated by Django 2.2.7 on 2020-07-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200713_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefeed',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
