# Generated by Django 2.2.7 on 2020-07-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20200713_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='corefeed',
            name='publish_status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1),
        ),
    ]
