# Generated by Django 2.2.7 on 2020-07-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_corefeed_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefeed',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
