# Generated by Django 2.2.7 on 2020-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20200713_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefeed',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
