# Generated by Django 2.2.7 on 2020-07-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20200714_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='short_description',
        ),
        migrations.AddField(
            model_name='feedback',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
