# Generated by Django 2.2.7 on 2020-07-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20200714_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answered',
            new_name='solved',
        ),
    ]
