# Generated by Django 2.2.7 on 2020-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20200714_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefeed',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
