# Generated by Django 2.2.7 on 2020-07-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20200714_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
