# Generated by Django 2.2.7 on 2020-04-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20200411_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
