# Generated by Django 2.2.7 on 2020-04-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20200411_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='idea',
        ),
    ]
