# Generated by Django 2.2.7 on 2020-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_remove_profile_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_limit',
            field=models.IntegerField(default=5),
        ),
    ]
