# Generated by Django 2.2.7 on 2020-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0005_profile_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_limit_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
