# Generated by Django 2.2.7 on 2020-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0007_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, max_length=160),
        ),
    ]
