# Generated by Django 2.2.7 on 2020-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='notification', to='usermgmt.Notification'),
        ),
    ]
