# Generated by Django 2.2.7 on 2020-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0023_auto_20200614_0005'),
        ('usermgmt', '0012_auto_20200615_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='idea.Tag'),
        ),
    ]
