# Generated by Django 2.2.7 on 2020-06-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0013_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fav_tags', to='idea.Tag'),
        ),
    ]
