# Generated by Django 2.2.7 on 2020-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0015_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_user',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
