# Generated by Django 2.2.7 on 2020-06-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0018_auto_20200626_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1),
        ),
    ]
