# Generated by Django 2.2.7 on 2020-07-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0019_auto_20200629_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment_setting',
            field=models.IntegerField(choices=[(1, 'Off'), (2, 'From Followers'), (3, 'From Everyone')], default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discover_setting',
            field=models.IntegerField(choices=[(1, 'Hide'), (2, 'Discoverable')], default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_setting',
            field=models.IntegerField(choices=[(1, 'Off'), (2, 'From Followers'), (3, 'From Everyone')], default=3),
        ),
    ]
