# Generated by Django 2.2.7 on 2020-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20200713_0117'),
        ('usermgmt', '0020_auto_20200709_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='core_feed',
            field=models.ManyToManyField(blank=True, related_name='core_feed', to='support.CoreFeed'),
        ),
    ]
