# Generated by Django 2.2.7 on 2020-07-16 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20200716_0804'),
        ('usermgmt', '0021_profile_core_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.Subscriber'),
        ),
    ]
