# Generated by Django 2.2.7 on 2020-07-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0022_profile_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
