# Generated by Django 2.2.7 on 2020-07-18 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0023_auto_20200717_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_limit_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
