# Generated by Django 2.2.7 on 2020-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0025_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_tag_filter',
            field=models.BooleanField(default=False),
        ),
    ]
