# Generated by Django 2.2.7 on 2020-08-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0026_profile_use_tag_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='use_tag_filter',
            field=models.IntegerField(choices=[(1, 'Filter Off'), (2, 'Filter On')], default=1),
        ),
    ]
