# Generated by Django 2.2.7 on 2020-08-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
    ]
