# Generated by Django 2.2.7 on 2020-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
