# Generated by Django 2.2.7 on 2020-08-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200803_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatpermission',
            old_name='permission',
            new_name='permitted',
        ),
    ]
