# Generated by Django 2.2.7 on 2020-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200803_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='key',
            field=models.SlugField(blank=True),
        ),
    ]
