# Generated by Django 2.2.7 on 2020-08-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200807_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='to_group',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='to_user',
        ),
    ]
