# Generated by Django 2.2.7 on 2020-08-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200807_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chat.ChatMessage'),
        ),
    ]
