# Generated by Django 2.2.7 on 2020-05-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Subscriber',
        ),
    ]
