# Generated by Django 2.2.7 on 2020-07-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200514_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='last_sent',
        ),
    ]
