# Generated by Django 2.2.7 on 2020-07-16 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20200715_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 4, 57, 135507)),
        ),
    ]
