# Generated by Django 2.2.7 on 2020-07-17 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_auto_20200717_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 2, 2, 47, 353745)),
        ),
    ]
