# Generated by Django 2.2.7 on 2020-07-17 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_auto_20200717_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 2, 3, 3, 359405)),
        ),
    ]
