# Generated by Django 2.2.7 on 2020-07-18 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0015_auto_20200717_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
