"""
Django settings for the_impossible project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, 'key.txt')) as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_URL = "usermgmt:login_page"

# Email 

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Use webfaction's smtp service
EMAIL_HOST = "smtp.example.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# Mail box
EMAIL_HOST_USER = "theimpossible_auto"
# This is the from email
DEFAULT_FROM_EMAIL = ""

with open(os.path.join(BASE_DIR, 'key.txt')) as f:
    EMAIL_HOST_PASSWORD = f.read().strip() 

TEMPLATED_EMAIL_DJANGO_SUBJECTS = {
    'explore':'Explore - The Impossible',
    'question':'Support - The Impossible',
    'verification':'Verification Code - The Impossible',
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'django_inlinecss',

    # All periodic tasks and tasks with long delay such as email sending
    # are processed later in the background to reduce website (view functions)
    # loading time 
    'background_task',

    'usermgmt',
    'idea',
    'userupload',
    'newsletter',
    'support',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Not auto installed
    'csp.middleware.CSPMiddleware',
]

# Security

# SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER = True

# CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_SECURE = True

# SECURE_SSL_REDIRECT = True

X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "same-origin"

#################
# Becareful with these below !!
# Only do these in production !!
# SECURE_HSTS_SECONDS = 604800 # 7 days
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
#################

# Content Security Policy

# Content Security Policy

CSP_DEFAULT_SRC = ("'self'",)

CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://stackpath.bootstrapcdn.com",
    # External fonts are also loaded as css
    "https://fonts.googleapis.com",
)

CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js",
    "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js",
)

CSP_IMG_SRC = (
    "'self'",
    "data:",
)

CSP_FONT_SRC = (
    "'self'",
    "fonts.gstatic.com",
    "https://fonts.googleapis.com",
)

ROOT_URLCONF = 'the_impossible.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"the_impossible/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_impossible.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "the_impossible/static")
]

# Change during deployment
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
MEDIA_URL = '/media/'

# Change during deployment
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
