# Generated by Django 2.2.7 on 2020-04-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['name']},
        ),
    ]
