# Generated by Django 2.2.7 on 2020-04-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_remove_profile_idea'),
        ('idea', '0002_auto_20200411_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Profile'),
            preserve_default=False,
        ),
    ]
