# Generated by Django 2.2.7 on 2020-04-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20200413_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='liked_user',
            field=models.ManyToManyField(blank=True, related_name='liked', to='usermgmt.Profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='viewed_user',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='usermgmt.Profile'),
        ),
    ]
