# Generated by Django 2.2.7 on 2020-04-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_auto_20200413_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='publish_stats',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Followers only')], default=1),
        ),
    ]
