# Generated by Django 2.2.7 on 2020-04-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_idea_publish_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
