# Generated by Django 2.2.7 on 2020-04-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_idea_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ManyToManyField(blank=True, to='idea.Idea')),
            ],
        ),
    ]
