# Generated by Django 2.2.7 on 2020-04-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_recommendedidea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedIdea',
        ),
    ]
