# Generated by Django 2.2.7 on 2020-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_delete_recommendedidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='header_img',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
