# Generated by Django 2.2.7 on 2020-04-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0012_auto_20200428_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='header_img',
            new_name='document',
        ),
    ]
