# Generated by Django 2.2.7 on 2020-05-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0014_auto_20200428_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='header_img',
        ),
    ]
