# Generated by Django 2.2.7 on 2020-05-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0017_auto_20200502_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='header_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userupload.File'),
        ),
    ]
