# Generated by Django 2.2.7 on 2020-05-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0006_auto_20200502_1543'),
        ('idea', '0018_auto_20200502_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='body_img',
            field=models.ManyToManyField(blank=True, related_name='body_image', to='userupload.File'),
        ),
    ]
