# Generated by Django 2.2.7 on 2020-06-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0006_profile_daily_limit_timestamp'),
        ('idea', '0021_auto_20200513_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='starred_user',
            field=models.ManyToManyField(blank=True, related_name='starred', to='usermgmt.Profile'),
        ),
    ]
