# Generated by Django 2.2.7 on 2020-06-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0022_idea_starred_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='publish_stats',
            new_name='publish_status',
        ),
    ]
