# Generated by Django 2.2.7 on 2020-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0023_auto_20200614_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='publish_status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Followers only'), (3, 'Public')], default=1),
        ),
    ]
