# Generated by Django 2.2.7 on 2020-06-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0025_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
