# Generated by Django 2.2.7 on 2020-06-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0026_auto_20200629_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='idea.Comment'),
        ),
    ]
