# Generated by Django 2.2.7 on 2020-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0027_auto_20200630_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='full_description',
            field=models.TextField(max_length=1000),
        ),
    ]
