# Generated by Django 2.2.7 on 2020-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0028_auto_20200702_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
