# Generated by Django 2.2.7 on 2020-08-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0031_auto_20200731_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='full_description',
            new_name='content',
        ),
    ]
